##
## EPITECH PROJECT, 2020
## Makefile
## File description:
## Makefile
##

all:
	make -C ./antman all
	make -C ./giantman all

clean:
	make -C ./antman clean
	make -C ./giantman clean

fclean: clean
	make -C ./antman fclean
	make -C ./giantman fclean

re: fclean all