##
## EPITECH PROJECT, 2020
## Makefile
## File description:
## Makefile
##

all:
	make -C ./generator all
	make -C ./solver all

clean:
	make -C ./generator clean
	make -C ./solver clean

fclean: clean
	make -C ./generator fclean
	make -C ./solver fclean

re: fclean all